steps:
- task: Maven@3
  displayName: "Maven: Build"

  inputs:
    mavenOptions: '-Xmx2048m'
    mavenPomFile: "pom.xml"

    javaHomeOption: "JDKVersion"
    jdkVersionOption: "$(jdk_version)"
    jdkArchitectureOption: "x64"
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

    goals: "package -Pbuild-extras"
    options: "--batch-mode"
